import type { Binding } from './engine';

export const defaultBindings: Binding[] = [
  { key: 'j', scope: 'list', action: 'focusNext' },
  { key: '↓', scope: 'list', action: 'focusNext' },
  { key: 'k', scope: 'list', action: 'focusPrev' },
  { key: '↑', scope: 'list', action: 'focusPrev' },
  { key: '↩', scope: 'list', action: 'open' },
  { key: 'o', scope: 'list', action: 'open' },
  { key: 'u', scope: 'thread', action: 'back' },
  { key: 'x', scope: 'list', action: 'toggleSelect' },
  { key: '⇧j', scope: 'list', action: 'extendDown' },
  { key: '⇧k', scope: 'list', action: 'extendUp' },
  { key: '⌘a', scope: 'list', action: 'selectAll' },
  { key: 'e', scope: 'list', action: 'archive' },
  { key: 'e', scope: 'thread', action: 'archive' },
  { key: '#', scope: 'list', action: 'trash' },
  { key: '⌫', scope: 'list', action: 'trash' },
  { key: '#', scope: 'thread', action: 'trash' },
  { key: '!', scope: 'list', action: 'spam' },
  { key: 's', scope: 'list', action: 'star' },
  { key: 's', scope: 'thread', action: 'star' },
  { key: '⇧u', scope: 'list', action: 'markUnread' },
  { key: '⇧i', scope: 'list', action: 'markRead' },
  { key: 'h', scope: 'list', action: 'snooze' },
  { key: 'h', scope: 'thread', action: 'snooze' },
  { key: 'l', scope: 'list', action: 'label' },
  { key: 'v', scope: 'list', action: 'move' },
  { key: 'z', scope: 'global', action: 'undo' },
  { key: '⌘z', scope: 'global', action: 'undo' },
  { key: 'r', scope: 'thread', action: 'reply' },
  { key: 'a', scope: 'thread', action: 'replyAll' },
  { key: 'f', scope: 'thread', action: 'forward' },
  { key: 'c', scope: 'global', action: 'compose' },
  { key: '⌘n', scope: 'global', action: 'compose' },
  { key: 'n', scope: 'thread', action: 'nextMsg' },
  { key: 'p', scope: 'thread', action: 'prevMsg' },
  { key: 'o', scope: 'thread', action: 'toggleMsg' },
  { key: ']', scope: 'thread', action: 'archiveNext' },
  { key: '[', scope: 'thread', action: 'archivePrev' },
  { key: '/', scope: 'global', action: 'search' },
  { key: '⌘k', scope: 'global', action: 'palette' },
  { key: 'g i', scope: 'global', action: 'goInbox' },
  { key: 'g s', scope: 'global', action: 'goStarred' },
  { key: 'g h', scope: 'global', action: 'goSnoozed' },
  { key: 'g t', scope: 'global', action: 'goSent' },
  { key: 'g d', scope: 'global', action: 'goDrafts' },
  { key: 'g a', scope: 'global', action: 'goArchive' },
  { key: '⌘1', scope: 'global', action: 'account1' },
  { key: '⌘2', scope: 'global', action: 'account2' },
  { key: '⌘0', scope: 'global', action: 'accountAll' },
  { key: '⌘\\', scope: 'global', action: 'toggleSidebar' },
  { key: '`', scope: 'global', action: 'cyclePane' },
  { key: '⌘,', scope: 'global', action: 'settings' },
  { key: '?', scope: 'global', action: 'help' },
  { key: '⌘r', scope: 'global', action: 'syncNow' },
];
